# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-18 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
