# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-18 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170618_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default=b'', max_length=500),
        ),
    ]
