# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-19 06:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20170619_1218'),
        ('accounts', '0003_auto_20170618_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='review',
            field=models.ManyToManyField(related_name='testinomial', through='review.Review', to=settings.AUTH_USER_MODEL),
        ),
    ]
