# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-19 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('accounts', '0008_auto_20170619_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='member_of', to='auth.Group'),
        ),
    ]
