# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-19 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20170619_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='member_of', to='auth.Group'),
        ),
    ]
