# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-19 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='info',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
